url: "http://aitbw.github.io"
baseurl: ""
title: "Angel Perez"
description: "Information Engineer, Backend Developer & Polyglot"

navbar-links:
  Posts: "posts"

avatar: "/img/avatar-icon.jpg"
round-avatar: true
author: Angel Perez

social-network-links:
  email: "aitbw@icloud.com"
  github: aitbw
  linkedin: angelperez93
  stackoverflow: "4844313/angel-perez"

rss-description: This website is a virtual proof that I'm awesome

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

date_format: "%B %-d, %Y"
timezone: "America/Caracas"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
